= hm2_modbus(9)

== NAME

hm2_modbus - A hostmot2 driver that implements the Modbus protocol using the
PktUART ports.

== SYNOPSIS

*loadrt hm2_modbus*

____
*ports* [default: <empty>]::
  A comma separated list of PktUART HAL names to use as Modbus hardware
  channel. Each must be matched with an MBCCB file specified in the *mbccbs*
  parameter. Example: ports="hm2_7i95.0.pktuart.0","hm2_5i25.0.pktuart.7"
*mbccbs* [default: <empty>]::
  A comma separated list of Modbus command control file paths to use for each
  PktUART port as specified in the *ports* parameter. The path should be an
  absolute path to prevent nasty surprises. Example:
  mbccbs="/path/to/rly-and-spindle.mbccb","/path/to/lightsparks.mbccb"
*debug* [default: -1]::
  Set the message level of the running process. The message level is set
  if *debug* is set to a positive value between 0 and 5, where 0 means no
  messages at all and 5 means everything. A value of -1 does not touch the
  current message level. +
  Caveat Emptor: changing the message level is process-wide and all modules
  within the process will spit out messages at the requested level. This may
  cause quite some clutter in your terminal.
____


== DESCRIPTION

The hm2_modbus driver implements the Modbus protocol and maps HAL pins to
Modbus devices' coils, inputs and registers. The mappings may be a complex set
and the configuration format is described in *mesambccc*(1).

The driver exports a set of HAL pins and parameters that can be used inspect
status and alter some settings in a live environment.

Up to eight instances are supported, which are instantiated by setting
the *ports* and *mbccbs* parameters. The instances are names 'hm2_modbus.0', 'hm2_modbus.1',...

The driver exports one function named 'process', which must be added to the
servo-thread _after_ hostmot2's read function and _before_ hostmot2's write
function.

[source,text]
----
addf hm2_7i96s.0.read     servo-thread
...
addf hm2_modbus.0.process servo-thread
...
addf hm2_7i96s.0.write    servo-thread
...
----

=== PARAMETERS

* 'baudrate' (HAL_U32, RO):
  The communication baudrate
* 'parity' (HAL_U32, RO):
  The communication parity (0=None, 1=Odd, 2=Even)
* 'stopbits' (HAL_U32, RO):
  The communication number of stopbits
* 'txdelay' (HAL_U32, RW):
  The inter-frame delay inserted after a packet in bit-times.
* 'rxdelay' (HAL_U32, RW):
  The inter-frame delay required before a packet is accepted in bit-times.
* 'drive-delay' (HAL_U32, RW):
  The transmitter wait time between enabling the transmitter and sending starts
  in bit-times.

There is normally no need to alter any parameters. Only the inter-frame delay
and drive delay may be altered at runtime to tune the hardware bus for badly
behaving devices. Any resulting values should be integrated in the mbccb file
to be set correctly as defaults.

=== PINS

The drives exposes the following pins:

* 'reset' (HAL_BIT, input):
  Reset all commands error counters and re-enable disabled commands.
* 'fault' (HAL_BIT, output):
  Indicates a fault condition.
* 'fault-command' (HAL_U32, output):
  The command index that caused the fault condition.
* 'last-error' (HAL_U32, output):
  The errno value of the error that cause the fault condition.

Each mbccb file will generate a set of pins as defined in the mbccb file. See
*mesambccc*(1) for details.

== SEE ALSO

*hostmot2*(9),
*mesambccc*(1).

== AUTHOR

This man page written by B.Stultiens, as part of the LinuxCNC project.

== REPORTING BUGS

Report bugs at https://github.com/LinuxCNC/linuxcnc/issues

== COPYRIGHT

Copyright © 2025 B.Stultiens

This is free software; see the source for copying conditions. There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
