= hm2_rp5spi(9)

== NAME

hm2_rp5spi - LinuxCNC HAL driver for the Mesa Electronics SPI Anything IO
boards, with HostMot2 firmware.

== SYNOPSIS

*loadrt hm2_rp5spi*

____
*config* [default: ""]::
  HostMot2 config strings, described in the *hostmot2*(9) manpage.
*spiclk_rate* [default: 25000]::
  Specify the SPI clock rate in kHz for each probed board. See *SPI
  CLOCK RATES* below. Each entry follows the *spi_probe* setting, where
  each probe takes the next value of the *spi_rate* list. A *spi_rate* of
  0 (zero) or less automatically selects the first rate in the list. You
  may truncate the list to the number of boards you use.
*spiclk_rate_rd* [default: same as *spiclk_rate*]::
  Specify the SPI read clock rate in kHz. Usually you read and write at
  the same speed. However, you may want to reduce the reading speed if
  the round-trip is too long (see *SPI CLOCK RATES* below). You may
  truncate the list to the number of boards you use.
*spi_pull_miso* [default: 1,1 (pull-down)]::
*spi_pull_mosi* [default: 0,0 (pull-off)]::
*spi_pull_sclk* [default: 0,0 (pull-off)]::
  Enable or disable pull-up/pull-down on the SPI lines for SPI ports 0
  and 1. A value of 0 disables any pull-up/down on the pin. A value of 1
  means pull-down and 2 means pull-up. The chip enable line(s) are always
  pull-up enabled.
*spi_probe* [default: 1]::
  Probe SPI port and CE lines for a card. This is a bit-field indicating
  which combinations of SPI and CE should be probed: - 1 = SPI0/CE0, - 2
  = SPI0/CE1, - 4 = SPI1/CE0, - 8 = SPI1/CE1, - 16 = SPI1/CE2. +
  The probe is performed exactly in above order. Any boards found will
  be numbered 0...4 in the order found. See also *INTERFACE CONFIGURATION*
  below. +
  It is an error if a probe fails and the driver will abort. The
  SPI0/SPI1 peripherals are located at GPIO pins (with 40-pin I/O header
  pin-number in parentheses): - SPI0: MOSI=10(19), MISO=9(21),
  SCLK=11(23), CE0=8(24), CE1=7(26) - SPI1: MOSI=20(38), MISO=19(35),
  SCLK=21(40), CE0=18(12), CE1=17(11), CE2=16(36).
*spi_noqueue* [default: 0 (off)]::
  Force disable queued command processing. Normally, all requests are
  queued if requested by upstream and sent in one bulk transfer. This
  reduces overhead significantly by up to 35%. Disabling the queue makes
  each transfer visible and more easily debug-able. Set to any non-zero
  value to disable the queue.
*spi_debug* [default: -1]::
  Set the message level of the running process. The message level is set
  if *spi_debug* is set to a positive value between 0 and 5, where 0
  means no messages at all and 5 means everything. A value of -1 does
  not touch the current message level. +
  Caveat Emptor: changing the message level is process-wide and all
  modules within the process will spit out messages at the requested
  level. This may cause quite some clutter in your terminal.
____

== DESCRIPTION

hm2_rp5spi is a device driver for the Raspberry Pi 5 that interfaces
Mesa's SPI based Anything I/O boards with SPI enabled HostMot2 firmware
to the LinuxCNC HAL. This driver is not based on the linux spidev
driver, but on a dedicated RP1 SPI hardware interface driver.

The supported boards are: 7I90HD, 7I43, 7C80 and 7C81.

The board must have a compatible firmware (like: 7i90_spi_*-bit,
7c80_*.bit and 7c81_*.bit) loaded on the board by the *mesaflash*(1)
program.

hm2_rp5spi is only available when LinuxCNC is configured with "uspace"
realtime. It works with Raspian and PREEMPT_RT kernel.

See also *NOTES* below.

== INTERFACE CONFIGURATION

Up to five devices boards are supported. Two on SPI0 and three on SPI1.
It is recommended that you, at most, use two devices and each device
connected to a separate SPI port. You can choose which CE lines you
prefer or fit the design and setup the *spi_probe* parameter to instruct
the driver where to search for the board(s).

== REALTIME PERFORMANCE OF THE RP1 SPI DRIVER

TBD.

== SPI CLOCK RATES

The SPI driver can provide frequencies well beyond what is acceptable
for any board. A safe value to start with would be 12.5 MHz
(spiclk_rate=12500) and then work your way up from there.

The SPI driver generates (very) discrete clock frequency values,
especially in the MHz range because of a simple clock divider structure.
The base frequency is 200 MHz and the divider for SPI0/SPI1 scales using
discrete factors. The following list specifies the *spiclk_rate* and
*spiclk_rate_rd* settings and the discrete SPI clock frequency (200 MHz
/ (2n) for n > 1):
 - 50000 - 50.000 MHz, - 33333 - 33.333 MHz, - 25000 - 25.000 MHz,
 - 20000 - 20.000 MHz, - 16666 - 16.666 MHz, - 14285 - 14.285 MHz,
 - 12500 - 12.500 MHz, - 11111 - 11.111 MHz, - 10000 - 10.000 MHz,
 - 9090 - 9.090 MHz, - ....

The lowest selectable SPI clock frequency is 4 kHz (spiclk_rate=4) for
SPI0 and SPI1, which is about the slowest possible rate. You should not
expect any real-time performance with such slow setting.

The highest SPI clock frequency is, theoretically, 100 MHz. However, you
will not be able to build any reliable hardware interface at that
frequency. The driver limits the clock to 50.0 MHz (cpiclk_rate=50000).
The chances are rather slim that you get the interface to work reliably
at this frequency. The board interface supports frequencies up to 50 MHz
and that is with perfect cabling and impedance matching (in write
direction only).

Writing to the board may be done faster than reading. This is especially
important if you have "long" wires or any buffers on the SPI-bus path.
You can set the read clock frequency to a lower value (using
*spiclk_rate_rd*) to counter the effects of the SPI-bus round-trip
needed for read actions. For example, you can write at 33.33 MHz and
read at 25.00 MHz.

The maximum SPI clock of the RP1 SPI driver has been tested up to
50 MHz write speed and 33 MHz read speed on the 7C80 and 7C81. However,
it is not recommended to run at the limit on production systems. A safe
setting would be to set one step below the maximum speeds.

== NOTES

It is *strongly* recommended that you unload/disable the kernel's SPI
drivers *dw_spi* and *dw_spi_mmio* (on Raspbian use the *raspi-config*
program's "Interface Options" configuration). The hm2_rp5spi driver
attempts to unload the kernel driver at startup if detected and restores
it at exit if initially loaded. However, there are no guarantees about
the effectiveness of the module unload/load actions.

*Warning*: having both kernel and user-space SPI drivers installed can
result in unexpected interactions and system instabilities.

The Raspberry Pi 5 *must* have an adequate 5V power supply and the power
should be properly decoupled. At high speeds and noise on the supply,
there is the possibility of strange behaviour if the noise gets out of
hand.

The 7C80 provides enough local power to the host via the interface
header if your external power supply is adequate (on connector TB6). The
7C81 needs an adequate external 5V power supply (on connector TB1) and
feeds it directly to the host interface header.

Also be sure to have a proper *active* heat-sink mounted on the
Raspberry 5 SoC or it will get too warm and may crash.

== SEE ALSO

hostmot2(9)

== LICENSE

GPL
